# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ivPYbwf8lHHnVj5iIve4SidkmpkqDTd7
"""

x, y = 0, 1
for i in range(15):
  print(x)
  x, y = y, x + y

