# -*- coding: utf-8 -*-
"""hello world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h6dzDYwAXprJMznrX1scc-X98aGXSoCB
"""

print("Hello World!")