# -*- coding: utf-8 -*-
"""positive integers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16SMiy9W4EJE1bXASBnW5lGCeDnERhnlu
"""

def print_positive_numbers(input_list):
    positive_numbers = [i for i in input_list if i > 0]
    print("Output:", positive_numbers)
list1 = [12, -7, 5, 64, -14]
print_positive_numbers(list1)

list2 = [12, 14, -95, 3]
print_positive_numbers(list2)