# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrqZObC8nqjIo1pTqENFfRKLYRSyaDgq
"""

print("Hello World!")